apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  timeout: 20m
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: loki-canary
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "0.14.0"
  values:
    podSecurityPolicy:
      enabled: false
    persistence:
      enabled: true
      size: 5Gi
    service:
      type: ClusterIP