apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    remediation:
      retries: 2
  upgrade:
    remediation:
      retries: 2
  values:
    controller:
      service:
        type: LoadBalancer   # <-- IMPORTANT: so you get an external IP for ingress controller