apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-app-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: nginx-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: 80
      interval: 30s
      path: /